apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-notes-app.fullname" . }}-canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "canary-notes-app.name" . }}-canary
